name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Basic tools (Git is required by python-for-android/Buildozer)
      - name: Install system deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            git zip unzip wget curl ca-certificates \
            openjdk-17-jdk python3-venv python3-pip \
            build-essential libssl-dev libffi-dev \
            libjpeg-dev libfreetype6-dev

      # 3) Cache the Android SDK between runs (big speed boost)
      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/android-sdk
          key: android-sdk-33-33.0.2

      # 4) Install Android SDK (cmdline-tools, platform-tools, build-tools with AIDL)
      - name: Install Android SDK
        run: |
          ANDROID_SDK="$GITHUB_WORKSPACE/android-sdk"
          mkdir -p "$ANDROID_SDK/cmdline-tools"
          if [ ! -d "$ANDROID_SDK/cmdline-tools/latest" ]; then
            wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
            unzip -q commandlinetools-linux-11076708_latest.zip -d "$ANDROID_SDK/cmdline-tools"
            mv "$ANDROID_SDK/cmdline-tools/cmdline-tools" "$ANDROID_SDK/cmdline-tools/latest"
          fi
          yes | "$ANDROID_SDK/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK" \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "cmdline-tools;latest"
          yes | "$ANDROID_SDK/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK" --licenses

      # 5) Set up Python and cache pip
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-py310

      # 6) Install Buildozer
      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.37

      # 7) Build APK
      - name: Build APK (debug)
        env:
          ANDROIDSDK: ${{ github.workspace }}/android-sdk
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
          PATH: ${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ env.PATH }}
        run: |
          buildozer android debug

      # 8) Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
