name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install host deps
      run: |
        sudo apt-get update -y
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-venv python3-pip \
          build-essential libssl-dev libffi-dev libjpeg-dev libfreetype6-dev

    - name: Install Android SDK (cmdline + build-tools + platform)
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip -q commandlinetools-linux-11076708_latest.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
          "platform-tools" "platforms;android-33" "build-tools;33.0.2" "cmdline-tools;latest"

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer==1.5.0 cython==0.29.37

    - name: Build APK
      env:
        ANDROIDSDK: ${{ github.workspace }}/android-sdk
        ANDROID_HOME: ${{ github.workspace }}/android-sdk
        PATH: ${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ env.PATH }}
      run: |
        export ANDROIDSDK="$GITHUB_WORKSPACE/android-sdk"
        export ANDROID_HOME="$GITHUB_WORKSPACE/android-sdk"
        export PATH="$ANDROIDSDK/platform-tools:$ANDROIDSDK/cmdline-tools/latest/bin:$PATH"
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
