name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Git is required by python-for-android/Buildozer
      - name: Install Git (before checkout just in case)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt-get install -y \
            zip unzip wget curl ca-certificates \
            openjdk-17-jdk python3-venv python3-pip \
            build-essential libssl-dev libffi-dev \
            libjpeg-dev libfreetype6-dev

      # Cache speeds up subsequent runs
      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/android-sdk
          key: android-sdk-33-33.0.2

      - name: Install Android SDK (cmdline, platforms, build-tools) and accept licenses
        env:
          ANDROID_SDK: ${{ github.workspace }}/android-sdk
        run: |
          set -e
          mkdir -p "$ANDROID_SDK/cmdline-tools"
          if [ ! -d "$ANDROID_SDK/cmdline-tools/latest" ]; then
            wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
            unzip -q commandlinetools-linux-11076708_latest.zip -d "$ANDROID_SDK/cmdline-tools"
            mv "$ANDROID_SDK/cmdline-tools/cmdline-tools" "$ANDROID_SDK/cmdline-tools/latest"
          fi
          yes | "$ANDROID_SDK/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK" \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "cmdline-tools;latest"
          yes | "$ANDROID_SDK/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK" --licenses

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-py310

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.37

      - name: Build APK (debug)
        env:
          ANDROIDSDK: ${{ github.workspace }}/android-sdk
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
          PATH: ${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ env.PATH }}
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
