name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install host deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y zip unzip openjdk-17-jdk python3-dev libffi-dev build-essential libssl-dev git
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.37
      - name: Build APK
        run: buildozer android debug
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
